import React, { useState, useRef, useCallback } from 'react';
import {
  View,
  Text,
  TextInput,
  TouchableOpacity,
  ScrollView,
  StyleSheet,
  ActivityIndicator,
  Alert,
  KeyboardAvoidingView,
  Platform,
  Keyboard,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { useStore, getDefaultGitHubAccount } from '../src/store/useStore';

// Lazy imports - loaded only when needed, not at startup
let _chatWithGemini: any = null;
let _generateFullProject: any = null;
let _createAgenticEngine: any = null;

const loadAIModules = async () => {
  if (!_chatWithGemini) {
    const gemini = require('../src/api/geminiApi');
    _chatWithGemini = gemini.chatWithGemini;
    _generateFullProject = gemini.generateFullProject;
  }
};

const loadEngineModules = async () => {
  if (!_createAgenticEngine) {
    const engine = require('../src/engine/AgenticEngine');
    _createAgenticEngine = engine.createAgenticEngine;
  }
};

export default function HomeScreen() {
  const [input, setInput] = useState('');
  const [buildStatus, setBuildStatus] = useState('');
  const [showActions, setShowActions] = useState(false);
  const router = useRouter();
  const scrollRef = useRef<ScrollView>(null);
  
  const { 
    messages, addMessage, isProcessing, setIsProcessing, 
    pendingFiles, setPendingFiles, linkedRepo, setLinkedRepo,
    autonomousMode, selfHealingEnabled,
    addProject
  } = useStore();
  
  const hasKey = useStore.getState().aiProviders.length > 0;
  const activeProvider = useStore.getState().aiProviders.find(
    p => p.id === useStore.getState().activeProviderId
  );
  const providerInfo = activeProvider ? { name: activeProvider.name, type: activeProvider.type } : null;
  const ghAccount = getDefaultGitHubAccount();
  const hasPendingFiles = pendingFiles && Object.keys(pendingFiles).length > 0;

  const scrollToBottom = useCallback(() => {
    setTimeout(() => scrollRef.current?.scrollToEnd({ animated: true }), 150);
  }, []);

  // Push to GitHub
  const pushToGitHub = useCallback(async () => {
    if (!ghAccount) {
      Alert.alert('No GitHub', 'Settings mein GitHub account add karo');
      router.push('/settings');
      return;
    }
    if (!hasPendingFiles) return;

    await loadEngineModules();
    if (!_createAgenticEngine) return;

    const projectName = useStore.getState().projects.slice(-1)[0]?.name || 'my-app';
    
    setShowActions(false);
    setBuildStatus('Pushing to GitHub...');
    
    try {
      const { GitHubAutonomousService } = require('../src/engine/AgenticEngine');
      const service = new GitHubAutonomousService(ghAccount.token, ghAccount.username);
      
      const repoFullName = await service.createRepository(
        projectName,
        'Generated by App Factory'
      );
      await new Promise(r => setTimeout(r, 3000));
      await service.pushFiles(repoFullName, pendingFiles!, 'Initial commit: App Factory');
      
      setLinkedRepo(repoFullName);
      setBuildStatus('');
      
      addMessage({ 
        role: 'ai', 
        content: `GitHub pe push ho gaya: ${repoFullName}\n\nGitHub Actions ab APK build karega. GitHub tab mein jaake status dekh sakte ho.` 
      });
      scrollToBottom();
    } catch (e: any) {
      setBuildStatus('');
      addMessage({ role: 'ai', content: `Push failed: ${e.message}` });
      scrollToBottom();
    }
  }, [ghAccount, hasPendingFiles, pendingFiles, setLinkedRepo, addMessage, scrollToBottom, router]);

  // Start autonomous build
  const startAutonomousBuild = useCallback(async () => {
    if (!ghAccount) {
      Alert.alert('No GitHub Account', 'Settings mein add karo');
      return;
    }

    await loadEngineModules();
    if (!_createAgenticEngine) return;

    const projectName = useStore.getState().projects.slice(-1)[0]?.name || 'my-app';
    
    setShowActions(false);
    setBuildStatus('Connecting to GitHub...');
    
    try {
      const projectEngine = _createAgenticEngine(projectName, 'App Factory project');
      const files = useStore.getState().pendingFiles;
      if (files) projectEngine.loadFiles(files);
      
      projectEngine.connectGitHub(ghAccount.token, ghAccount.username);
      
      setBuildStatus('Creating repo & pushing...');
      const repoFullName = await projectEngine.createAndPush(projectName);
      setLinkedRepo(repoFullName);
      
      addMessage({ 
        role: 'ai', 
        content: `Repo created: ${repoFullName}\n\nAutonomous build shuru ho rahi hai${selfHealingEnabled ? ' (self-healing ON)' : ''}...` 
      });
      scrollToBottom();

      await projectEngine.autonomousBuild(
        (status: string) => setBuildStatus(status),
        (result: any) => {
          setBuildStatus('');
          if (result.success) {
            addMessage({ role: 'ai', content: `BUILD SUCCESSFUL!\n\nAPK download karo: GitHub Actions > Artifacts` });
          } else {
            addMessage({ role: 'ai', content: `Build failed: ${result.failedStep || 'Unknown error'}\n\n${result.logs?.slice(0, 300) || ''}` });
          }
          scrollToBottom();
        }
      );
    } catch (e: any) {
      setBuildStatus('');
      addMessage({ role: 'ai', content: `Error: ${e.message}` });
      scrollToBottom();
    }
  }, [ghAccount, selfHealingEnabled, setLinkedRepo, addMessage, scrollToBottom]);

  // Send message with full conversation context
  const send = async () => {
    if (!input.trim()) return;
    
    if (!hasKey) {
      Alert.alert('No API Key', 'Settings mein AI provider key add karo');
      router.push('/settings');
      return;
    }

    Keyboard.dismiss();
    addMessage({ role: 'user', content: input });
    const userInput = input;
    setInput('');
    setIsProcessing(true);
    setShowActions(false);
    scrollToBottom();

    try {
      await loadAIModules();
      
      // Build chat history for context
      const chatHistory = useStore.getState().messages.map(m => ({
        role: m.role,
        content: m.content,
      }));

      // Check if first-time project request
      const isFirstProjectRequest = !hasPendingFiles && 
        /app|build|create|बनाओ|banao|project|calculator|todo|game|chat/i.test(userInput);

      let res;
      if (isFirstProjectRequest) {
        addMessage({ role: 'ai', content: 'Complete project generate ho raha hai...' });
        scrollToBottom();
        res = await _generateFullProject(userInput);
      } else {
        // Send with full context - chat history + pending files
        res = await _chatWithGemini(userInput, {
          chatHistory,
          existingFiles: pendingFiles || undefined,
          hasPendingFiles: !!hasPendingFiles,
        });
      }
      
      if ((res.action === 'write_code' || res.action === 'fix_error') && res.files) {
        const projectName = userInput
          .split(' ')
          .slice(0, 3)
          .join('-')
          .toLowerCase()
          .replace(/[^a-z0-9-]/g, '') || 'my-app';
        
        const fileCount = Object.keys(res.files).length;
        const fileList = Object.keys(res.files).slice(0, 12).join('\n- ');
        
        addMessage({ 
          role: 'ai', 
          content: `${fileCount} files generate ho gayi:\n\n- ${fileList}${fileCount > 12 ? `\n- ... aur ${fileCount - 12} more` : ''}\n\nPlan: ${res.plan || 'Project ready'}\n\nLibraries: ${res.libraries?.join(', ') || 'Standard'}` 
        });
        
        setPendingFiles(res.files);
        
        addProject({
          name: projectName,
          description: userInput,
          files: res.files,
          repo: null,
          buildStatus: 'idle',
          lastBuildLog: '',
        });
        
        // Show action buttons
        setShowActions(true);
        scrollToBottom();
      } else {
        addMessage({ role: 'ai', content: res.message || 'Done!' });
        scrollToBottom();
      }
    } catch (e: any) {
      addMessage({ role: 'ai', content: `Error: ${e.message}` });
      scrollToBottom();
    } finally {
      setIsProcessing(false);
    }
  };

  return (
    <SafeAreaView style={styles.container} edges={['top']}>
      {/* Header */}
      <View style={styles.header}>
        <View style={styles.headerLeft}>
          <View style={styles.logo}>
            <Ionicons name="flash" size={24} color="#A78BFA" />
          </View>
          <View>
            <Text style={styles.title}>App Factory</Text>
            <Text style={styles.subtitle}>
              {providerInfo?.name || 'Autonomous AI Builder'}
            </Text>
          </View>
        </View>
        <View style={styles.headerRight}>
          <TouchableOpacity style={styles.iconBtn} onPress={() => router.push('/projects')} data-testid="projects-btn">
            <Ionicons name="folder" size={22} color="#A78BFA" />
          </TouchableOpacity>
          <TouchableOpacity style={styles.iconBtn} onPress={() => router.push('/github')} data-testid="github-btn">
            <Ionicons name="logo-github" size={22} color="#A78BFA" />
          </TouchableOpacity>
          <TouchableOpacity style={styles.iconBtn} onPress={() => router.push('/settings')} data-testid="settings-btn">
            <Ionicons name="settings" size={22} color="#A78BFA" />
          </TouchableOpacity>
        </View>
      </View>

      {/* Build Status */}
      {buildStatus ? (
        <View style={styles.buildBanner}>
          <ActivityIndicator size="small" color="#FFF" />
          <Text style={styles.buildText}>{buildStatus}</Text>
        </View>
      ) : null}

      {/* Linked Repo */}
      {linkedRepo ? (
        <View style={styles.repoBanner}>
          <Ionicons name="git-branch" size={14} color="#10B981" />
          <Text style={styles.repoText}>{linkedRepo}</Text>
        </View>
      ) : null}

      {/* No API Key Warning */}
      {!hasKey ? (
        <TouchableOpacity style={styles.warning} onPress={() => router.push('/settings')}>
          <Ionicons name="warning" size={16} color="#FCD34D" />
          <Text style={styles.warningText}>No API Key - Tap to configure</Text>
        </TouchableOpacity>
      ) : null}

      <KeyboardAvoidingView 
        style={styles.keyboardArea}
        behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
        keyboardVerticalOffset={Platform.OS === 'ios' ? 0 : 0}
      >
        {/* Chat Area */}
        <ScrollView 
          ref={scrollRef} 
          style={styles.chat}
          contentContainerStyle={styles.chatContent}
          keyboardShouldPersistTaps="handled"
          keyboardDismissMode="interactive"
        >
          {messages.length === 0 ? (
            <View style={styles.empty}>
              <View style={styles.emptyIcon}>
                <Ionicons name="rocket" size={44} color="#A78BFA" />
              </View>
              <Text style={styles.emptyTitle}>App Factory AI</Text>
              <Text style={styles.emptyText}>
                Apna app idea batao - complete project generate hoga, GitHub pe push hoga, APK build hoga.
              </Text>
              
              <View style={styles.features}>
                <View style={styles.featureRow}>
                  <View style={styles.feature}>
                    <Ionicons name="folder-open" size={18} color="#A78BFA" />
                    <Text style={styles.featureText}>Multi-File Projects</Text>
                  </View>
                  <View style={styles.feature}>
                    <Ionicons name="git-branch" size={18} color="#10B981" />
                    <Text style={styles.featureText}>GitHub Auto-Push</Text>
                  </View>
                </View>
                <View style={styles.featureRow}>
                  <View style={styles.feature}>
                    <Ionicons name="build" size={18} color="#F59E0B" />
                    <Text style={styles.featureText}>Self-Healing Builds</Text>
                  </View>
                  <View style={styles.feature}>
                    <Ionicons name="phone-portrait" size={18} color="#EF4444" />
                    <Text style={styles.featureText}>Native Modules</Text>
                  </View>
                </View>
              </View>

              <Text style={styles.tryText}>Try: "Calculator app banao"</Text>
            </View>
          ) : null}

          {messages.map((msg, i) => (
            <View key={msg.id || i} style={[styles.bubble, msg.role === 'user' ? styles.userBubble : styles.aiBubble]}>
              <View style={styles.bubbleHeader}>
                <Ionicons name={msg.role === 'user' ? 'person' : 'flash'} size={14} color="#A78BFA" />
                <Text style={styles.roleText}>{msg.role === 'user' ? 'You' : 'Agentic AI'}</Text>
              </View>
              <Text style={styles.msgText} selectable>{msg.content}</Text>
            </View>
          ))}

          {/* Action Buttons after code generation */}
          {showActions && hasPendingFiles && !isProcessing ? (
            <View style={styles.actionBox}>
              <Text style={styles.actionTitle}>Code ready! Aage kya karna hai?</Text>
              <View style={styles.actionBtns}>
                <TouchableOpacity 
                  style={[styles.actionBtn, styles.actionPush]}
                  onPress={pushToGitHub}
                  data-testid="action-push-github"
                >
                  <Ionicons name="cloud-upload" size={18} color="#FFF" />
                  <Text style={styles.actionBtnText}>GitHub Push</Text>
                </TouchableOpacity>
                <TouchableOpacity 
                  style={[styles.actionBtn, styles.actionBuild]}
                  onPress={startAutonomousBuild}
                  data-testid="action-auto-build"
                >
                  <Ionicons name="rocket" size={18} color="#FFF" />
                  <Text style={styles.actionBtnText}>Auto Build</Text>
                </TouchableOpacity>
              </View>
              <View style={styles.actionBtns}>
                <TouchableOpacity 
                  style={[styles.actionBtn, styles.actionView]}
                  onPress={() => router.push('/projects')}
                  data-testid="action-view-code"
                >
                  <Ionicons name="code-slash" size={18} color="#FFF" />
                  <Text style={styles.actionBtnText}>Code Dekho</Text>
                </TouchableOpacity>
                <TouchableOpacity 
                  style={[styles.actionBtn, styles.actionChat]}
                  onPress={() => setShowActions(false)}
                  data-testid="action-continue-chat"
                >
                  <Ionicons name="chatbubble" size={18} color="#FFF" />
                  <Text style={styles.actionBtnText}>Chat Continue</Text>
                </TouchableOpacity>
              </View>
            </View>
          ) : null}

          {isProcessing ? (
            <View style={styles.loading}>
              <ActivityIndicator color="#A78BFA" />
              <Text style={styles.loadingText}>AI soch raha hai...</Text>
            </View>
          ) : null}
        </ScrollView>

        {/* Input */}
        <View style={styles.inputBox}>
          <TextInput
            style={styles.input}
            placeholder={hasPendingFiles ? "Kuch aur karna hai? Batao..." : "App idea describe karo..."}
            placeholderTextColor="#6B7280"
            value={input}
            onChangeText={setInput}
            multiline
            maxLength={2000}
            onFocus={scrollToBottom}
            data-testid="chat-input"
          />
          <TouchableOpacity 
            style={[styles.sendBtn, (!input.trim() || isProcessing) && styles.sendDisabled]} 
            onPress={send}
            disabled={!input.trim() || isProcessing}
            data-testid="send-btn"
          >
            {isProcessing ? (
              <ActivityIndicator color="#0A0A0F" size="small" />
            ) : (
              <Ionicons name="send" size={20} color="#0A0A0F" />
            )}
          </TouchableOpacity>
        </View>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#0A0A0F' },
  keyboardArea: { flex: 1 },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#1F1F2E' },
  headerLeft: { flexDirection: 'row', alignItems: 'center' },
  logo: { width: 40, height: 40, borderRadius: 10, backgroundColor: '#1F1F2E', alignItems: 'center', justifyContent: 'center', marginRight: 10 },
  title: { color: '#FFF', fontSize: 18, fontWeight: 'bold' },
  subtitle: { color: '#A78BFA', fontSize: 11, fontWeight: '600' },
  headerRight: { flexDirection: 'row', gap: 6 },
  iconBtn: { width: 38, height: 38, borderRadius: 10, backgroundColor: '#1F1F2E', alignItems: 'center', justifyContent: 'center' },
  buildBanner: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', padding: 10, backgroundColor: '#7C3AED', gap: 8 },
  buildText: { color: '#FFF', fontSize: 12, fontWeight: '600' },
  repoBanner: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', padding: 6, backgroundColor: '#064E3B', gap: 6 },
  repoText: { color: '#10B981', fontSize: 11, fontWeight: '600' },
  warning: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', padding: 8, backgroundColor: '#78350F', gap: 6 },
  warningText: { color: '#FCD34D', fontSize: 12, fontWeight: '600' },
  chat: { flex: 1 },
  chatContent: { padding: 14, paddingBottom: 20 },
  empty: { alignItems: 'center', paddingVertical: 30 },
  emptyIcon: { width: 80, height: 80, borderRadius: 20, backgroundColor: '#1F1F2E', alignItems: 'center', justifyContent: 'center', marginBottom: 16 },
  emptyTitle: { color: '#FFF', fontSize: 20, fontWeight: 'bold', marginBottom: 8 },
  emptyText: { color: '#9CA3AF', fontSize: 13, textAlign: 'center', paddingHorizontal: 20, lineHeight: 20, marginBottom: 20 },
  features: { gap: 8, marginBottom: 16 },
  featureRow: { flexDirection: 'row', gap: 8 },
  feature: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#1F1F2E', paddingVertical: 8, paddingHorizontal: 12, borderRadius: 8, flex: 1 },
  featureText: { color: '#D1D5DB', fontSize: 11 },
  tryText: { color: '#6B7280', fontSize: 12, fontStyle: 'italic' },
  bubble: { padding: 12, borderRadius: 14, marginBottom: 10, maxWidth: '90%' },
  userBubble: { backgroundColor: '#3B2D5B', alignSelf: 'flex-end' },
  aiBubble: { backgroundColor: '#1F1F2E', alignSelf: 'flex-start', borderWidth: 1, borderColor: '#2D2D3D' },
  bubbleHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 4, gap: 5 },
  roleText: { color: '#9CA3AF', fontSize: 11, fontWeight: '600' },
  msgText: { color: '#E5E7EB', fontSize: 13, lineHeight: 20 },
  loading: { flexDirection: 'row', alignItems: 'center', padding: 14, gap: 10 },
  loadingText: { color: '#9CA3AF', fontSize: 13 },
  // Action buttons
  actionBox: { backgroundColor: '#12121A', borderRadius: 14, padding: 14, marginBottom: 10, borderWidth: 1, borderColor: '#A78BFA30' },
  actionTitle: { color: '#A78BFA', fontSize: 14, fontWeight: '700', marginBottom: 10, textAlign: 'center' },
  actionBtns: { flexDirection: 'row', gap: 8, marginBottom: 8 },
  actionBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', padding: 12, borderRadius: 10, gap: 6 },
  actionPush: { backgroundColor: '#7C3AED' },
  actionBuild: { backgroundColor: '#059669' },
  actionView: { backgroundColor: '#2563EB' },
  actionChat: { backgroundColor: '#374151' },
  actionBtnText: { color: '#FFF', fontSize: 13, fontWeight: '700' },
  // Input
  inputBox: { flexDirection: 'row', padding: 10, backgroundColor: '#12121A', borderTopWidth: 1, borderTopColor: '#1F1F2E', gap: 8, alignItems: 'flex-end' },
  input: { flex: 1, backgroundColor: '#1F1F2E', color: '#FFF', borderRadius: 14, paddingHorizontal: 14, paddingVertical: 10, maxHeight: 80, fontSize: 14 },
  sendBtn: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#A78BFA', alignItems: 'center', justifyContent: 'center' },
  sendDisabled: { opacity: 0.5 },
});
