import React, { useState, useCallback } from 'react';
import {
  View,
  Text,
  TouchableOpacity,
  ScrollView,
  StyleSheet,
  Alert,
  Modal,
  ActivityIndicator,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useStore, getDefaultGitHubAccount, Project } from '../src/store/useStore';

// Lazy loaded
let _GitHubService: any = null;
const loadGitHubService = async () => {
  if (!_GitHubService) {
    const engine = require('../src/engine/AgenticEngine');
    _GitHubService = engine.GitHubAutonomousService;
  }
  return _GitHubService;
};

type ViewMode = 'list' | 'detail';

export default function Projects() {
  const router = useRouter();
  const { projects, removeProject, updateProject, setLinkedRepo } = useStore();
  const [selectedProject, setSelectedProject] = useState<Project | null>(null);
  const [selectedFile, setSelectedFile] = useState<string | null>(null);
  const [viewMode, setViewMode] = useState<ViewMode>('list');
  const [pushing, setPushing] = useState(false);
  const [expandedFolders, setExpandedFolders] = useState<Set<string>>(new Set());

  const ghAccount = getDefaultGitHubAccount();

  // Build folder tree from flat file paths
  const buildFileTree = useCallback((files: Record<string, string>) => {
    const tree: Record<string, any> = {};
    
    for (const path of Object.keys(files).sort()) {
      const parts = path.split('/');
      let current = tree;
      
      for (let i = 0; i < parts.length; i++) {
        const part = parts[i];
        if (i === parts.length - 1) {
          // File
          current[part] = { type: 'file', path };
        } else {
          // Folder
          if (!current[part]) {
            current[part] = { type: 'folder', children: {} };
          }
          current = current[part].children;
        }
      }
    }
    
    return tree;
  }, []);

  const toggleFolder = (folderPath: string) => {
    setExpandedFolders(prev => {
      const next = new Set(prev);
      if (next.has(folderPath)) {
        next.delete(folderPath);
      } else {
        next.add(folderPath);
      }
      return next;
    });
  };

  // Push project to GitHub
  const pushToGitHub = async (project: Project) => {
    if (!ghAccount) {
      Alert.alert('No GitHub', 'Add a GitHub account in Settings first');
      router.push('/settings');
      return;
    }

    setPushing(true);
    try {
      const Service = await loadGitHubService();
      const service = new Service(ghAccount.token, ghAccount.username);
      const repoName = project.name.toLowerCase().replace(/[^a-z0-9-]/g, '-');
      
      const repoFullName = await service.createRepository(
        repoName,
        project.description || 'Generated by App Factory'
      );

      await new Promise(r => setTimeout(r, 3000));
      await service.pushFiles(repoFullName, project.files, 'Initial commit: App Factory generated project');

      updateProject(project.id, { repo: repoFullName, buildStatus: 'building' });
      setLinkedRepo(repoFullName);

      Alert.alert(
        'Pushed!',
        `Code pushed to ${repoFullName}\n\nGitHub Actions will build APK automatically.`,
        [
          { text: 'OK' },
          { text: 'View Builds', onPress: () => router.push('/github') },
        ]
      );
    } catch (e: any) {
      Alert.alert('Error', e.message);
    } finally {
      setPushing(false);
    }
  };

  const deleteProject = (project: Project) => {
    Alert.alert(
      'Delete Project?',
      `"${project.name}" permanently delete hoga. Are you sure?`,
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Delete',
          style: 'destructive',
          onPress: () => {
            removeProject(project.id);
            if (selectedProject?.id === project.id) {
              setSelectedProject(null);
              setViewMode('list');
            }
          },
        },
      ]
    );
  };

  const openProject = (project: Project) => {
    setSelectedProject(project);
    setSelectedFile(null);
    setViewMode('detail');
    // Auto-expand root folders
    const rootFolders = new Set<string>();
    Object.keys(project.files).forEach(path => {
      const firstPart = path.split('/')[0];
      if (path.includes('/')) rootFolders.add(firstPart);
    });
    setExpandedFolders(rootFolders);
  };

  const getFileIcon = (filename: string): string => {
    if (filename.endsWith('.tsx') || filename.endsWith('.ts')) return 'logo-react';
    if (filename.endsWith('.json')) return 'code-slash';
    if (filename.endsWith('.yml') || filename.endsWith('.yaml')) return 'git-branch';
    if (filename.endsWith('.java')) return 'cafe';
    if (filename.endsWith('.xml')) return 'code';
    if (filename.endsWith('.md')) return 'document-text';
    return 'document';
  };

  const getFileColor = (filename: string): string => {
    if (filename.endsWith('.tsx')) return '#61DAFB';
    if (filename.endsWith('.ts')) return '#3178C6';
    if (filename.endsWith('.json')) return '#F59E0B';
    if (filename.endsWith('.yml')) return '#10B981';
    if (filename.endsWith('.java')) return '#EF4444';
    if (filename.endsWith('.xml')) return '#A78BFA';
    return '#9CA3AF';
  };

  const getBuildStatusColor = (status: string) => {
    switch (status) {
      case 'success': return '#10B981';
      case 'failed': return '#EF4444';
      case 'building': return '#F59E0B';
      default: return '#6B7280';
    }
  };

  const getBuildStatusIcon = (status: string): string => {
    switch (status) {
      case 'success': return 'checkmark-circle';
      case 'failed': return 'close-circle';
      case 'building': return 'time';
      default: return 'ellipse-outline';
    }
  };

  // Render file tree recursively
  const renderTreeNode = (name: string, node: any, depth: number, parentPath: string) => {
    const currentPath = parentPath ? `${parentPath}/${name}` : name;

    if (node.type === 'file') {
      const isSelected = selectedFile === node.path;
      return (
        <TouchableOpacity
          key={currentPath}
          style={[styles.fileRow, { paddingLeft: 16 + depth * 16 }, isSelected && styles.fileRowActive]}
          onPress={() => setSelectedFile(node.path)}
          data-testid={`file-${node.path.replace(/[/.]/g, '-')}`}
        >
          <Ionicons name={getFileIcon(name) as any} size={14} color={getFileColor(name)} />
          <Text style={[styles.fileName, isSelected && styles.fileNameActive]} numberOfLines={1}>
            {name}
          </Text>
        </TouchableOpacity>
      );
    }

    if (node.type === 'folder') {
      const isExpanded = expandedFolders.has(currentPath);
      return (
        <View key={currentPath}>
          <TouchableOpacity
            style={[styles.folderRow, { paddingLeft: 16 + depth * 16 }]}
            onPress={() => toggleFolder(currentPath)}
          >
            <Ionicons
              name={isExpanded ? 'chevron-down' : 'chevron-forward'}
              size={12}
              color="#6B7280"
            />
            <Ionicons name="folder" size={14} color="#F59E0B" />
            <Text style={styles.folderName}>{name}</Text>
          </TouchableOpacity>
          {isExpanded &&
            Object.entries(node.children)
              .sort(([, a]: any, [, b]: any) => {
                if (a.type === 'folder' && b.type !== 'folder') return -1;
                if (a.type !== 'folder' && b.type === 'folder') return 1;
                return 0;
              })
              .map(([childName, childNode]) =>
                renderTreeNode(childName, childNode, depth + 1, currentPath)
              )}
        </View>
      );
    }

    return null;
  };

  // ==================== LIST VIEW ====================
  if (viewMode === 'list') {
    return (
      <ScrollView style={styles.container} contentContainerStyle={styles.content}>
        {projects.length === 0 ? (
          <View style={styles.empty}>
            <View style={styles.emptyIcon}>
              <Ionicons name="folder-open" size={40} color="#A78BFA" />
            </View>
            <Text style={styles.emptyTitle}>No Projects Yet</Text>
            <Text style={styles.emptyText}>
              AI se chat karke apna pehla app project generate karo.
            </Text>
            <TouchableOpacity
              style={styles.createBtn}
              onPress={() => router.push('/')}
              data-testid="create-project-btn"
            >
              <Ionicons name="add" size={20} color="#000" />
              <Text style={styles.createBtnText}>Create New App</Text>
            </TouchableOpacity>
          </View>
        ) : (
          <>
            <View style={styles.listHeader}>
              <Text style={styles.listTitle}>Your Projects ({projects.length})</Text>
              <TouchableOpacity onPress={() => router.push('/')}>
                <Ionicons name="add-circle" size={28} color="#A78BFA" />
              </TouchableOpacity>
            </View>

            {projects.map((project) => (
              <TouchableOpacity
                key={project.id}
                style={styles.projectCard}
                onPress={() => openProject(project)}
                data-testid={`project-card-${project.id}`}
              >
                <View style={styles.cardHeader}>
                  <View style={styles.cardLeft}>
                    <View style={styles.cardIcon}>
                      <Ionicons name="cube" size={22} color="#A78BFA" />
                    </View>
                    <View style={styles.cardInfo}>
                      <Text style={styles.cardName} numberOfLines={1}>{project.name}</Text>
                      <Text style={styles.cardDesc} numberOfLines={1}>
                        {project.description || 'No description'}
                      </Text>
                    </View>
                  </View>
                  <Ionicons name="chevron-forward" size={20} color="#6B7280" />
                </View>

                <View style={styles.cardMeta}>
                  <View style={styles.metaItem}>
                    <Ionicons name="document" size={12} color="#6B7280" />
                    <Text style={styles.metaText}>
                      {Object.keys(project.files).length} files
                    </Text>
                  </View>

                  {project.repo && (
                    <View style={styles.metaItem}>
                      <Ionicons name="logo-github" size={12} color="#6B7280" />
                      <Text style={styles.metaText} numberOfLines={1}>{project.repo}</Text>
                    </View>
                  )}

                  <View style={styles.metaItem}>
                    <Ionicons
                      name={getBuildStatusIcon(project.buildStatus) as any}
                      size={12}
                      color={getBuildStatusColor(project.buildStatus)}
                    />
                    <Text style={[styles.metaText, { color: getBuildStatusColor(project.buildStatus) }]}>
                      {project.buildStatus}
                    </Text>
                  </View>

                  <Text style={styles.metaDate}>
                    {new Date(project.createdAt).toLocaleDateString()}
                  </Text>
                </View>
              </TouchableOpacity>
            ))}
          </>
        )}
      </ScrollView>
    );
  }

  // ==================== DETAIL VIEW ====================
  if (!selectedProject) return null;

  const fileTree = buildFileTree(selectedProject.files);
  const fileContent = selectedFile ? selectedProject.files[selectedFile] : null;

  return (
    <View style={styles.detailContainer}>
      {/* Top Bar */}
      <View style={styles.detailHeader}>
        <TouchableOpacity onPress={() => setViewMode('list')} style={styles.backBtn}>
          <Ionicons name="arrow-back" size={20} color="#FFF" />
        </TouchableOpacity>
        <View style={styles.detailTitleBox}>
          <Text style={styles.detailTitle} numberOfLines={1}>{selectedProject.name}</Text>
          <Text style={styles.detailSub}>
            {Object.keys(selectedProject.files).length} files
            {selectedProject.repo ? ` | ${selectedProject.repo}` : ''}
          </Text>
        </View>
        <View style={styles.detailActions}>
          <TouchableOpacity
            style={styles.actionBtn}
            onPress={() => pushToGitHub(selectedProject)}
            disabled={pushing}
            data-testid="push-github-btn"
          >
            {pushing ? (
              <ActivityIndicator size="small" color="#FFF" />
            ) : (
              <Ionicons name="cloud-upload" size={18} color="#FFF" />
            )}
          </TouchableOpacity>
          <TouchableOpacity
            style={[styles.actionBtn, styles.deleteBtn]}
            onPress={() => deleteProject(selectedProject)}
            data-testid="delete-project-btn"
          >
            <Ionicons name="trash" size={18} color="#EF4444" />
          </TouchableOpacity>
        </View>
      </View>

      {/* Build Status Banner */}
      {selectedProject.repo && (
        <View style={[styles.statusBanner, { backgroundColor: getBuildStatusColor(selectedProject.buildStatus) + '20' }]}>
          <Ionicons
            name={getBuildStatusIcon(selectedProject.buildStatus) as any}
            size={16}
            color={getBuildStatusColor(selectedProject.buildStatus)}
          />
          <Text style={[styles.statusText, { color: getBuildStatusColor(selectedProject.buildStatus) }]}>
            Build: {selectedProject.buildStatus.toUpperCase()}
          </Text>
          <TouchableOpacity onPress={() => router.push('/github')}>
            <Text style={styles.viewBuildsLink}>View Builds</Text>
          </TouchableOpacity>
        </View>
      )}

      {/* Split View: File Tree + Code Viewer */}
      <View style={styles.splitView}>
        {/* File Tree (Left Panel) */}
        <ScrollView style={styles.fileTreePanel}>
          <Text style={styles.panelTitle}>FILES</Text>
          {Object.entries(fileTree)
            .sort(([, a]: any, [, b]: any) => {
              if (a.type === 'folder' && b.type !== 'folder') return -1;
              if (a.type !== 'folder' && b.type === 'folder') return 1;
              return 0;
            })
            .map(([name, node]) => renderTreeNode(name, node, 0, ''))}
        </ScrollView>

        {/* Code Viewer (Right Panel) */}
        <View style={styles.codePanel}>
          {selectedFile && fileContent ? (
            <>
              <View style={styles.codeHeader}>
                <Ionicons name={getFileIcon(selectedFile) as any} size={14} color={getFileColor(selectedFile)} />
                <Text style={styles.codeFileName} numberOfLines={1}>{selectedFile}</Text>
                <Text style={styles.codeLines}>{fileContent.split('\n').length} lines</Text>
              </View>
              <ScrollView style={styles.codeBody} horizontal>
                <ScrollView nestedScrollEnabled>
                  <Text style={styles.codeText} selectable>
                    {fileContent}
                  </Text>
                </ScrollView>
              </ScrollView>
            </>
          ) : (
            <View style={styles.noFileSelected}>
              <Ionicons name="code-slash" size={36} color="#374151" />
              <Text style={styles.noFileText}>Select a file to view its code</Text>
            </View>
          )}
        </View>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#0A0A0F' },
  content: { padding: 16, paddingBottom: 40 },
  
  // Empty state
  empty: { alignItems: 'center', paddingVertical: 60 },
  emptyIcon: { width: 80, height: 80, borderRadius: 24, backgroundColor: '#1F1F2E', alignItems: 'center', justifyContent: 'center', marginBottom: 20 },
  emptyTitle: { color: '#FFF', fontSize: 20, fontWeight: 'bold', marginBottom: 8 },
  emptyText: { color: '#9CA3AF', fontSize: 14, textAlign: 'center', paddingHorizontal: 32, lineHeight: 22, marginBottom: 24 },
  createBtn: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#A78BFA', paddingHorizontal: 24, paddingVertical: 14, borderRadius: 12, gap: 8 },
  createBtnText: { color: '#000', fontSize: 15, fontWeight: 'bold' },

  // List View
  listHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  listTitle: { color: '#FFF', fontSize: 18, fontWeight: 'bold' },

  projectCard: { backgroundColor: '#12121A', borderRadius: 14, padding: 14, marginBottom: 12, borderWidth: 1, borderColor: '#1F1F2E' },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  cardLeft: { flexDirection: 'row', alignItems: 'center', flex: 1, gap: 12 },
  cardIcon: { width: 44, height: 44, borderRadius: 12, backgroundColor: '#1F1F2E', alignItems: 'center', justifyContent: 'center' },
  cardInfo: { flex: 1 },
  cardName: { color: '#FFF', fontSize: 16, fontWeight: '700' },
  cardDesc: { color: '#6B7280', fontSize: 12, marginTop: 2 },
  cardMeta: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 12 },
  metaItem: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  metaText: { color: '#6B7280', fontSize: 11 },
  metaDate: { color: '#374151', fontSize: 11, marginLeft: 'auto' },

  // Detail View
  detailContainer: { flex: 1, backgroundColor: '#0A0A0F' },
  detailHeader: { flexDirection: 'row', alignItems: 'center', padding: 12, borderBottomWidth: 1, borderBottomColor: '#1F1F2E', gap: 10 },
  backBtn: { width: 36, height: 36, borderRadius: 10, backgroundColor: '#1F1F2E', alignItems: 'center', justifyContent: 'center' },
  detailTitleBox: { flex: 1 },
  detailTitle: { color: '#FFF', fontSize: 16, fontWeight: 'bold' },
  detailSub: { color: '#6B7280', fontSize: 11, marginTop: 2 },
  detailActions: { flexDirection: 'row', gap: 6 },
  actionBtn: { width: 36, height: 36, borderRadius: 10, backgroundColor: '#1F1F2E', alignItems: 'center', justifyContent: 'center' },
  deleteBtn: { backgroundColor: '#1C1C1C' },

  statusBanner: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, paddingVertical: 8, gap: 8 },
  statusText: { fontSize: 12, fontWeight: '700', flex: 1 },
  viewBuildsLink: { color: '#A78BFA', fontSize: 12, fontWeight: '600' },

  // Split View
  splitView: { flex: 1, flexDirection: 'row' },

  // File Tree
  fileTreePanel: { width: '35%', borderRightWidth: 1, borderRightColor: '#1F1F2E', backgroundColor: '#0D0D14' },
  panelTitle: { color: '#6B7280', fontSize: 10, fontWeight: '800', letterSpacing: 1, paddingHorizontal: 12, paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: '#1F1F2E' },
  folderRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 6, paddingRight: 8, gap: 4 },
  folderName: { color: '#D1D5DB', fontSize: 12, fontWeight: '600' },
  fileRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 5, paddingRight: 8, gap: 6 },
  fileRowActive: { backgroundColor: '#1F1F2E' },
  fileName: { color: '#9CA3AF', fontSize: 11, flex: 1 },
  fileNameActive: { color: '#FFF' },

  // Code Viewer
  codePanel: { flex: 1, backgroundColor: '#0A0A0F' },
  codeHeader: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: '#1F1F2E', gap: 6 },
  codeFileName: { color: '#D1D5DB', fontSize: 12, fontWeight: '600', flex: 1 },
  codeLines: { color: '#374151', fontSize: 10 },
  codeBody: { flex: 1, padding: 12 },
  codeText: { color: '#D1D5DB', fontSize: 11, fontFamily: 'monospace', lineHeight: 18 },
  noFileSelected: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12 },
  noFileText: { color: '#374151', fontSize: 13 },
});
